[2025-08-01T15:52:57.939+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-01T15:52:57.975+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ml_pipeline.evaluate manual__2025-08-01T15:52:30.072924+00:00 [queued]>
[2025-08-01T15:52:57.986+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ml_pipeline.evaluate manual__2025-08-01T15:52:30.072924+00:00 [queued]>
[2025-08-01T15:52:57.986+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-08-01T15:52:58.004+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): evaluate> on 2025-08-01 15:52:30.072924+00:00
[2025-08-01T15:52:58.016+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=246) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-08-01T15:52:58.018+0000] {standard_task_runner.py:64} INFO - Started process 255 to run task
[2025-08-01T15:52:58.016+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline', 'evaluate', 'manual__2025-08-01T15:52:30.072924+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline.py', '--cfg-path', '/tmp/tmpq7ub6pa2']
[2025-08-01T15:52:58.019+0000] {standard_task_runner.py:91} INFO - Job 13: Subtask evaluate
[2025-08-01T15:52:58.037+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-08-01T15:52:58.092+0000] {task_command.py:426} INFO - Running <TaskInstance: ml_pipeline.evaluate manual__2025-08-01T15:52:30.072924+00:00 [running]> on host 9b25a94ed79c
[2025-08-01T15:52:58.184+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ml_pipeline' AIRFLOW_CTX_TASK_ID='evaluate' AIRFLOW_CTX_EXECUTION_DATE='2025-08-01T15:52:30.072924+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-01T15:52:30.072924+00:00'
[2025-08-01T15:52:58.186+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-01T15:52:58.200+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-01T15:52:58.201+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: evaluate_model() missing 2 required positional arguments: 'model' and 'test_data'
[2025-08-01T15:52:58.212+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=ml_pipeline, task_id=evaluate, run_id=manual__2025-08-01T15:52:30.072924+00:00, execution_date=20250801T155230, start_date=20250801T155257, end_date=20250801T155258
[2025-08-01T15:52:58.224+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 13 for task evaluate (evaluate_model() missing 2 required positional arguments: 'model' and 'test_data'; 255)
[2025-08-01T15:52:58.273+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-08-01T15:52:58.293+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-01T15:52:58.297+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
