[2025-08-01T16:22:00.207+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-01T16:22:00.260+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ml_pipeline.train __airflow_temporary_run_2025-08-01T16:21:48.030524+00:00__ [queued]>
[2025-08-01T16:22:00.283+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ml_pipeline.train __airflow_temporary_run_2025-08-01T16:21:48.030524+00:00__ [queued]>
[2025-08-01T16:22:00.287+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-08-01T16:22:00.323+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): train> on 2025-08-01 00:00:00+00:00
[2025-08-01T16:22:00.361+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=919) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-08-01T16:22:00.358+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline', 'train', '__***_temporary_run_2025-08-01T16:21:48.030524+00:00__', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline.py', '--cfg-path', '/tmp/tmpugh6mrj5']
[2025-08-01T16:22:00.372+0000] {standard_task_runner.py:91} INFO - Job 19: Subtask train
[2025-08-01T16:22:00.369+0000] {standard_task_runner.py:64} INFO - Started process 932 to run task
[2025-08-01T16:22:00.414+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-08-01T16:22:00.526+0000] {task_command.py:426} INFO - Running <TaskInstance: ml_pipeline.train __airflow_temporary_run_2025-08-01T16:21:48.030524+00:00__ [running]> on host 9b25a94ed79c
[2025-08-01T16:22:00.698+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ml_pipeline' AIRFLOW_CTX_TASK_ID='train' AIRFLOW_CTX_EXECUTION_DATE='2025-08-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='__***_temporary_run_2025-08-01T16:21:48.030524+00:00__'
[2025-08-01T16:22:00.703+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-01T16:22:00.997+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/joblib/parallel.py:1379 UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
[2025-08-01T16:22:00.999+0000] {logging_mixin.py:188} INFO - Fitting 3 folds for each of 12 candidates, totalling 36 fits
[2025-08-01T16:22:01.224+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/xgboost/training.py:183 UserWarning: [16:22:01] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.
[2025-08-01T16:22:05.733+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/xgboost/training.py:183 UserWarning: [16:22:05] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.
[2025-08-01T16:22:07.513+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/xgboost/training.py:183 UserWarning: [16:22:07] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.
[2025-08-01T16:22:08.867+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/xgboost/training.py:183 UserWarning: [16:22:08] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.
[2025-08-01T16:22:09.060+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/xgboost/training.py:183 UserWarning: [16:22:09] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.
[2025-08-01T16:22:09.241+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/xgboost/training.py:183 UserWarning: [16:22:09] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.
[2025-08-01T16:22:09.409+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/xgboost/training.py:183 UserWarning: [16:22:09] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.
[2025-08-01T16:22:09.544+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/xgboost/training.py:183 UserWarning: [16:22:09] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.
[2025-08-01T16:22:09.710+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/xgboost/training.py:183 UserWarning: [16:22:09] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.
[2025-08-01T16:22:09.887+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/xgboost/training.py:183 UserWarning: [16:22:09] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.
[2025-08-01T16:22:10.221+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/xgboost/training.py:183 UserWarning: [16:22:10] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.
[2025-08-01T16:22:13.324+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/xgboost/training.py:183 UserWarning: [16:22:13] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.
[2025-08-01T16:22:13.565+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/xgboost/training.py:183 UserWarning: [16:22:13] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.
[2025-08-01T16:22:13.748+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/xgboost/training.py:183 UserWarning: [16:22:13] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.
[2025-08-01T16:22:13.970+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/xgboost/training.py:183 UserWarning: [16:22:13] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.
[2025-08-01T16:22:14.163+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/xgboost/training.py:183 UserWarning: [16:22:14] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.
[2025-08-01T16:22:14.526+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/xgboost/training.py:183 UserWarning: [16:22:14] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.
[2025-08-01T16:22:14.870+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/xgboost/training.py:183 UserWarning: [16:22:14] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.
[2025-08-01T16:22:15.278+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/xgboost/training.py:183 UserWarning: [16:22:15] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.
[2025-08-01T16:22:15.386+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/xgboost/training.py:183 UserWarning: [16:22:15] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.
[2025-08-01T16:22:15.494+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/xgboost/training.py:183 UserWarning: [16:22:15] WARNING: /workspace/src/learner.cc:738:
Parameters: { "use_label_encoder" } are not used.
[2025-08-01T16:22:15.575+0000] {local_task_job_runner.py:313} WARNING - State of this instance has been externally set to None. Terminating instance.
[2025-08-01T16:22:15.577+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-08-01T16:22:15.580+0000] {process_utils.py:132} INFO - Sending 15 to group 932. PIDs of all processes in the group: [932]
[2025-08-01T16:22:15.586+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 932
[2025-08-01T16:22:15.598+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-08-01T16:22:15.599+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-01T16:22:15.610+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/model_training.py", line 32, in train_model
    grid_search.fit(X_train, y_train)
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 1365, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/model_selection/_search.py", line 1051, in fit
    self._run_search(evaluate_candidates)
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/model_selection/_search.py", line 1605, in _run_search
    evaluate_candidates(ParameterGrid(self.param_grid))
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/model_selection/_search.py", line 997, in evaluate_candidates
    out = parallel(
          ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/parallel.py", line 82, in __call__
    return super().__call__(iterable_with_config_and_warning_filters)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/joblib/parallel.py", line 1986, in __call__
    return output if self.return_generator else list(output)
                                                ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/joblib/parallel.py", line 1914, in _get_sequential_output
    res = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/parallel.py", line 147, in __call__
    return self.function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/model_selection/_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/airflow/.local/lib/python3.12/site-packages/xgboost/core.py", line 729, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/xgboost/sklearn.py", line 1683, in fit
    self._Booster = train(
                    ^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/xgboost/core.py", line 729, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/xgboost/training.py", line 183, in train
    bst.update(dtrain, iteration=i, fobj=obj)
  File "/home/airflow/.local/lib/python3.12/site-packages/xgboost/core.py", line 2247, in update
    _LIB.XGBoosterUpdateOneIter(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2613, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2025-08-01T16:22:15.630+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=ml_pipeline, task_id=train, run_id=__***_temporary_run_2025-08-01T16:21:48.030524+00:00__, execution_date=20250801T000000, start_date=20250801T162200, end_date=20250801T162215
[2025-08-01T16:22:15.645+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 19 for task train ((psycopg2.errors.ForeignKeyViolation) insert or update on table "task_fail" violates foreign key constraint "task_fail_ti_fkey"
DETAIL:  Key (dag_id, task_id, run_id, map_index)=(ml_pipeline, train, __airflow_temporary_run_2025-08-01T16:21:48.030524+00:00__, -1) is not present in table "task_instance".

[SQL: INSERT INTO task_fail (task_id, dag_id, run_id, map_index, start_date, end_date, duration) VALUES (%(task_id)s, %(dag_id)s, %(run_id)s, %(map_index)s, %(start_date)s, %(end_date)s, %(duration)s) RETURNING task_fail.id]
[parameters: {'task_id': 'train', 'dag_id': 'ml_pipeline', 'run_id': '__airflow_temporary_run_2025-08-01T16:21:48.030524+00:00__', 'map_index': -1, 'start_date': datetime.datetime(2025, 8, 1, 16, 22, 0, 264228, tzinfo=Timezone('UTC')), 'end_date': datetime.datetime(2025, 8, 1, 16, 22, 15, 629606, tzinfo=Timezone('UTC')), 'duration': 15}]
(Background on this error at: https://sqlalche.me/e/14/gkpj); 932)
[2025-08-01T16:22:15.679+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=932, status='terminated', exitcode=1, started='16:21:59') (932) terminated with exit code 1
